name: dart_bloc_concurrency
description: Custom event transformers. Built to be used with the bloc state management package.
version: 2.0.0
repository: https://github.com/mj12358/dart-bloc-concurrency

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  stream_transform: ^2.1.1

dev_dependencies:
  dart_lintz: 1.2.3
  test: 1.26.2
